spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:tc:postgresql:16-alpine:///testdb
  jpa:
    hibernate:
      ddl-auto: create-drop
  kafka:
    bootstrap-servers: localhost:9092
jwt:
  secret: test-secret